workflows:
  hello-world:
    name: Hello world workflow
    scripts:
        - echo "Hello World!" 
        scripts:

  - name: Build for iOS         # Name of the section

    script: flutter build ios   # The script(s) to be run in that section
  scripts:

  - &increment_build_number       # Defined section 

    name: Increment build number 

    script: agvtool new-version -all $(($PROJECT_BUILD_NUMBER +1))
    scripts:

  - script1

  - *increment_build_number       # Reused section

  - script3
  definitions: 

  env_versions: &env_versions

    xcode: latest 

    cocoapods: default
    workflows: 

  ios-release: 

    name: iOS release 

    environment: 

      << : *env_versions
      

workflows:

  my-workflow:

    name: My workflow name

    labels:

      - QA

      - ${TENANT_NAME}

    instance_type: mac_mini_m2

    max_build_duration: 60

    inputs: # more information about build inputs:https://docs.codemagic.io/knowledge-codemagic/build-inputs/

      name: # input ID

        description: Input description

        default: Codemagic

    environment:

      groups:

        - group_name

      vars:

        PUBLIC_ENV_VAR: "value here"

      flutter: stable

      xcode: latest

    cache:

      cache_paths:

        - ~/.pub-cache

    triggering:

      events:

        - push

      branch_patterns:

        - pattern: '*'

          include: true

          source: true

      cancel_previous_builds: false

    scripts:

      - echo "Hello, ${{ inputs.name }}"

      - ...

    artifacts:

      - build/**/outputs/bundle/**/*.aab

    publishing:

      email:

        recipients:

          - name@example.com

      scripts:

        - echo 'Post-publish script'
workflows:

  my-workflow:                   # workflow ID

    name: My workflow name       # workflow name displayed in Codemagic UI

    instance_type: mac_mini_m2   # machine instance type

    max_build_duration: 60       # build duration in minutes (min 1, max 120)

    environment:

    cache:

    triggering:

    scripts:

    artifacts: 

    publishing: 
    